name: radiology
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # packages for icons
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  # packages for fonts management
  font_awesome_flutter: ^10.7.0
  # packages for alert in a nice design
  awesome_dialog: ^3.2.1
  # packages for customize clippers for designs
  flutter_custom_clippers: ^2.1.0
  flutter_lints: ^3.0.0
  # package for keep data in local source
  shared_preferences: ^2.2.3
  # packages for firebase management
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  # packages for state management using bloc or cubit
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # packages for video player
  video_player: ^2.8.6
  flick_video_player: ^0.8.0
  # package for get pics from phone
  image_picker: ^1.1.1
  # packages for providing path for images and files according to path on phone
  path_provider: ^2.1.3
  # packages for download files from server to phone
  http: ^1.2.1
  open_filex: ^4.4.0
  # package for link launching
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/svg/



  fonts:

    - family: Edu
      fonts:
        - asset: assets/fonts/EduTASBeginner-VariableFont_wght.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: Garet
      fonts:
        - asset: assets/fonts/garet/Garet-Book.ttf
        - asset: assets/fonts/garet/Garet-Heavy.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf

